name: pa_arif_uts
description: Project UTS BeautyNail.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0' # Menggunakan rentang yang benar untuk SDK 3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Dependencies untuk Maps dan File Handling
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  image_picker: ^1.1.1
  
  # Dependencies untuk Autentikasi dan API
  http: ^1.2.1 # Untuk komunikasi HTTP ke Flask
  google_sign_in: ^6.2.6 # Untuk Login Google
  shared_preferences: ^2.2.2 # Untuk data non-sensitif (opsional)
  flutter_secure_storage: ^9.0.0 # Wajib untuk menyimpan JWT/token

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Pastikan ini hanya ada satu kali

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    # Pastikan file google_logo.png ada di folder assets